#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/20-php-fpm ]; then
	### Start php-fpm
	echo 'Initialization Complete' >/tmp/state/20-php-fpm
fi

echo ''
echo '** [php-fpm] Starting php-fpm..'
exec mkdir -p /www/logs/php-fpm 
exec chown -R www-data:www-data /www/logs/php-fpm
exec s6-setuidgid www-data /usr/sbin/php-fpm7 -F;
exec php-fpm -d date.timezone=${TZ} -d expose_php=0
